---
title: "p8105_hw6_ak4123"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
set.seed(1)
```

Create a city_state variable (e.g. “Baltimore, MD”), and a binary variable indicating whether the homicide is solved. Omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO – these don’t report victim race. Also omit Tulsa, AL – this is a data entry mistake. 
``` {r}
homicides = read.csv("./data/homicide-data.csv")

homicides = homicides %>% 
  mutate(city_state = paste(city, state, sep = ", "),
         resolution = as.numeric(disposition == "Closed by arrest"),
         victim_race_binary = case_when(
           victim_race == "Asian" ~ "Non-White",
           victim_race == "Black" ~ "Non-White",
           victim_race == "Hispanic" ~ "Non-White",
           victim_race == "Other" ~ "Non-White",
           victim_race == "Unknown" ~ "Non-White",
           victim_race == "White" ~ "White"
         ),
         victim_race = factor(victim_race_binary, levels = c("White", "Non-White")),
         victim_age = as.numeric(as.character(victim_age))
  ) %>% 
  filter(city_state != "Dallas, TX" & city_state != "Phoenix, AZ" & city_state != "Kansas City, MO" & city_state != "Tulsa, AL")
```